# hugo.toml

baseURL = "https://profdrkdc.github.io/Vegan-BioTech-Report/"
title = "Vegan BioTech Report"
theme = "ananke"
defaultContentLanguage = "en"

[services.googleAnalytics]
  ID = "OYKwPNShOlUwg8ifiRNKgPhXRz8QFMQDZoggyWcXzTw"

[outputs]
  home = ["HTML", "RSS"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2