name: Weekly Content Generation

on:
  schedule:
    # Draait elke maandag om 08:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      skip_content_generation:
        description: 'Sla de content generatie stappen over.'
        required: false
        type: boolean
        default: false
      skip_blogger_publish:
        description: 'Sla de publicatie naar Blogger over.'
        required: false
        type: boolean
        default: false
      skip_social_publish:
        description: 'Sla de publicatie naar sociale media over.'
        required: false
        type: boolean
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for google-github-actions/auth@v2
      contents: write # <-- NIEUW: Toestaan om naar de repository te schrijven

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Generate and Publish All Content
        env:
          # AI Provider Keys
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          
          # Blogger Configuration
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
          PUBLISH_BLOGGER: 'true'

        run: |
          echo "--- Step 1: Generating all content... ---"
          python -m src.run_pipeline \
            ${{ github.event.inputs.skip_content_generation == 'true' && '--skip-content-generation' || '' }}             ${{ github.event.inputs.skip_blogger_publish == 'true' && '--skip-blogger-publish' || '' }}             ${{ github.event.inputs.skip_social_publish == 'true' && '--skip-social-publish' || '' }}
          
          # De publicatielogica zit nu in run_pipeline.py, dus de aparte stappen zijn niet meer nodig.
          # De social media publicatie kan eventueel een aparte stap blijven als dat wenselijk is.
          # Voor nu gaan we ervan uit dat de hoofd-pipeline alles afhandelt.
          # echo "--- Step 2: Publishing articles to Ghost... ---"
          # python src/publish_ghost.py # Deze stap wordt nu overgeslagen

      - name: Commit and Push Generated Content
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add content/ raw.json curated.json social_posts.json longread_outline.json
          git commit -m "feat: Add generated content from workflow run" || echo "No changes to commit"
          git push
