name: Weekly Content Generation and Deploy

on:
  push:
    branches:
      - main
  schedule:
    # Draait elke maandag om 08:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      skip_content_generation:
        description: 'Sla de content generatie stappen over (om bv. de site opnieuw te deployen).'
        required: false
        type: boolean
        default: false
      skip_website_deploy:
        description: 'Sla de publicatie naar GitHub Pages over.'
        required: false
        type: boolean
        default: false
      skip_social_publish:
        description: 'Sla de publicatie naar sociale media over.'
        required: false
        type: boolean
        default: false

jobs:
  # JOB 1: Genereer alle content en data bestanden
  generate-content:
    runs-on: ubuntu-latest
    outputs:
      content_generated: ${{ steps.commit.outputs.changes_detected }}
    permissions:
      contents: write 

    # --- DEZE LOGICA IS NU ROBUUSTER ---
    # Draait alleen als:
    # 1. Het een geplande run is (dan genereert het altijd content)
    # 2. OF het een handmatige run is EN de 'skip_content_generation' VLAG NIET is aangevinkt
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.skip_content_generation != 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Content Generation Pipeline
        env:
          SITE_BASE_URL: "https://profdrkdc.github.io/Vegan-BioTech-Report/"
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          python3 -m src.run_pipeline

      - name: Commit and Push Generated Content
        id: commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add content/ raw.json curated.json social_posts.json longread_outline.json published_post_url.txt
          if ! git diff --staged --quiet; then
            git commit -m "feat(content): Add generated content from workflow run"
            git push
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

  # JOB 2: Bouw de website
  build-website:
    runs-on: ubuntu-latest
    # Deze job heeft 'generate-content' nodig als die draait,
    # MAAR als 'generate-content' werd overgeslagen (omdat we alleen willen deployen),
    # dan hoeft deze er niet op te wachten.
    # Ook, als 'skip_website_deploy' is aangevinkt, slaan we deze job over.
    needs: generate-content
    if: >
      github.event.inputs.skip_website_deploy != 'true' && (
        (github.event.inputs.skip_content_generation == 'true') ||
        (needs.generate-content.result == 'success' && needs.generate-content.outputs.content_generated == 'true') ||
        (github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.inputs.skip_content_generation != 'true') # Extra check for initial push where no content was generated, but we still want to deploy
      )
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        run: hugo --cleanDestinationDir --minify --baseURL ${{ steps.pages.outputs.base_url }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # JOB 3: Publiceer de website naar GitHub Pages
  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-website
    if: needs.build-website.result == 'success'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # JOB 4: Publiceer naar sociale media nadat de site live is
  publish-social:
    runs-on: ubuntu-latest
    needs: deploy-pages
    if: success() && github.event.inputs.skip_social_publish != 'true'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Publish to Social Media
        env:
          AI_API_TYPE: "google"
          AI_MODEL_ID: "gemini-1.5-flash-latest" 
          AI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_API_BASE_URL: ${{ secrets.MASTODON_API_BASE_URL }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python3 -m src.publish_social